### ISSUE TITLE
Race condition between associating connections and removing them

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#61]
A client opening a connection and then removing it before the server associates the connection with a player is able to cause a crash.

## Steps to Reproduce (in theory)
- Open connection to server
- Send LOGIN packet
- Send close packet within the same frame
- server tries to associate the player with a connection that doesn't exist

## Stack Trace
These are the relevant frames from the stack trace
```
   9: airmash_server::types::connection::{{impl}}::associate::{{closure}}
             at D:\Projects\Projects\airmash\airmash-server\server\src\types\connection.rs:114
  10: airmash_server::systems::handlers::game::on_join::init_connection::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\systems\handlers\game\on_join\init_connection.rs:34
  11: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
  12: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
```

And here is the full stack trace
```
ERROR 2018-11-04T21:16:17Z: airmash_server::types::connection: Attempted to associate non-existent connection ConnectionId(259) with player Entity(65, Generation(6))
thread 'main' panicked at 'Nonexistent connection id ConnectionId(259)', server\src\types\connection.rs:114:4
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:476
   7: std::panicking::continue_panic_fmt
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:390
   8: std::panicking::begin_panic_fmt
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:345
   9: airmash_server::types::connection::{{impl}}::associate::{{closure}}
             at D:\Projects\Projects\airmash\airmash-server\server\src\types\connection.rs:114
  10: airmash_server::systems::handlers::game::on_join::init_connection::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\systems\handlers\game\on_join\init_connection.rs:34
  11: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
  12: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
  13: shred::dispatch::stage::Stage::execute_seq
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:111
  14: shred::dispatch::stage::Stage::execute_seq
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:111
  15: futures::stream::for_each::{{impl}}::poll<futures::stream::map_err::MapErr<futures::stream::take_while::TakeWhile<tokio_timer::interval::Interval, closure, core::result::Result<bool, tokio_timer::error::Error>>, closure>,closure,core::result::Result<(), ()>>
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\stream\for_each.rs:46
  16: futures::future::{{impl}}::poll
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\mod.rs:113
  17: futures::future::{{impl}}::poll
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\mod.rs:113
  18: futures::future::{{impl}}::poll
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\mod.rs:113
  19: futures::future::{{impl}}::poll
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\mod.rs:113
  20: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  21: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  22: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  23: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  24: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  25: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  26: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  27: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  28: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  29: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\mod.rs:396
  30: tokio_current_thread::scheduler::Scheduler<tokio_reactor::Handle>::tick<tokio_reactor::Handle>
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\scheduler.rs:333
  31: tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::tick
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\lib.rs:605
  32: tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::tick
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\lib.rs:605
  33: tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::tick
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\lib.rs:605
  34: std::thread::local::LocalKey<core::cell::Cell<tokio_executor::global::State>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  35: std::thread::local::LocalKey<core::cell::Cell<tokio_executor::global::State>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  36: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  37: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  38: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  39: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  40: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  41: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>>::try_with
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\thread\local.rs:300
  42: tokio_reactor::with_default
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-reactor-0.1.6\src\lib.rs:212
  43: tokio_reactor::with_default
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-reactor-0.1.6\src\lib.rs:212
  44: tokio_reactor::with_default
             at D:\Users\#####\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-reactor-0.1.6\src\lib.rs:212
  45: airmash_server::builder::AirmashServer<str*>::run<str*>
             at D:\Projects\Projects\airmash\airmash-server\server\src\builder.rs:256
  46: airmash_server_ffa::main
             at .\src\main.rs:35
  47: std::rt::lang_start::{{closure}}
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\rt.rs:74
  48: std::rt::lang_start::{{closure}}
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\rt.rs:74
  49: std::rt::lang_start::{{closure}}
             at \rustc\04fdb44f5ccb6f909cf0f768781afa483e97097c\src\libstd\rt.rs:74
  50: std::rt::lang_start_internal::{{closure}}
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\rt.rs:59
  51: std::rt::lang_start_internal::{{closure}}
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\rt.rs:59
  52: panic_unwind::__rust_maybe_catch_panic
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libpanic_unwind\lib.rs:102
  53: std::panicking::try
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:289
  54: std::panicking::try
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:289
  55: std::panicking::try
             at /rustc/04fdb44f5ccb6f909cf0f768781afa483e97097c\src/libstd\panicking.rs:289
  56: main
  57: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  58: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  59: BaseThreadInitThunk
  60: RtlUserThreadStart
```

## Probable Fixes
There's two ways to go about fixing this:
- Adjust system dependencies so that this can't happen (i.e. make the system that associates connections run before the one that removes them)
- Add a check before associating a connection to ensure that it exists

The 1st solution is cleaner but will require more digging to figure out the right systems. It's also possible that this interaction happens across multiple iterations of the main loop which will make the 2nd solution the only viable one.

## Some Extra Info
The system that associates the connection is `systems::handlers::game::on_join::init_connection`. The one that removes it is `handlers::onclose`.

If you'd like to tackle this issue feel free to ask questions here or on the gitter channel (see the README).

**Comment by BlackCrawler** [comment]
CTF server crashed with this error 
`thread 'main' panicked at 'Nonexistent connection id ConnectionId(2228)', server/src/types/connection.rs:94:4`
It happened when 16 ctf bots were connecting simultaneously.

**Comment by derps-airmash** [comment]
This happened on FFA today too, sometimes it happens twice or more in one day, other times (like the past 2 weeks), not at all

**Comment by derps-airmash** [comment]
wrap your server in a restart loop :)
