### ISSUE TITLE
Server Crash when disconnecting large numbers of bots

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#71]
Looks like this caused an event to be fired with an invalid id. Not sure the root cause though.
Here's the crash log:
```
thread '<unnamed>' panicked at 'Player did not have a plane component!', libcore\option.rs:1008:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\panicking.rs:476
   7: std::panicking::continue_panic_fmt
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libcore\panicking.rs:77
  10: core::option::expect_failed
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libcore\option.rs:1008
  11: airmash_server::systems::handlers::game::on_player_hit::inflict_damage::{{impl}}::on_event
             at D:\Projects\Projects\airmash\airmash-server\server\src\systems\handlers\game\on_player_hit\inflict_damage.rs:52
  12: airmash_server::utils::event_handler::{{impl}}::run<airmash_server::systems::handlers::game::on_player_hit::inflict_damage::InflictDamage>
             at D:\Projects\Projects\airmash\airmash-server\server\src\utils\event_handler.rs:50
  13: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
  14: airmash_server::dispatch::syswrapper::{{impl}}::run
             at D:\Projects\Projects\airmash\airmash-server\server\src\dispatch\syswrapper.rs:50
  15: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  16: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  17: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  18: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  19: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  20: shred::dispatch::stage::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.7.1\src\dispatch\stage.rs:96
  21: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  22: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  23: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  24: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  25: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libpanic_unwind\lib.rs:102
  26: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  27: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  28: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  29: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  30: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  31: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  32: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  33: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  34: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  35: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  36: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  37: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libpanic_unwind\lib.rs:102
  38: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  39: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  40: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  41: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  42: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  43: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  44: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  45: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  46: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  47: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  48: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:410
  49: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libpanic_unwind\lib.rs:102
  50: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  51: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  52: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  53: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  54: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  55: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  56: rayon_core::join::join_context
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\join\mod.rs:116
  57: rayon::iter::plumbing::bridge_producer_consumer
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:391
  58: rayon::iter::plumbing::bridge_producer_consumer
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.0.3\src\iter\plumbing\mod.rs:391
  59: rayon_core::job::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  60: rayon_core::job::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  61: rayon_core::job::{{impl}}::execute::{{closure}}
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  62: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libpanic_unwind\lib.rs:102
  63: rayon_core::job::{{impl}}::execute<rayon_core::latch::LockLatch,closure,()>
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:113
  64: rayon_core::job::JobRef::execute
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:60
  65: rayon_core::job::JobRef::execute
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:60
  66: rayon_core::job::JobRef::execute
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\job.rs:60
  67: rayon_core::registry::WorkerThread::wait_until
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:544
  68: rayon_core::registry::WorkerThread::wait_until
             at D:\Users\sean-lynch\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.4.1\src\registry.rs:544
  69: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\thread\mod.rs:477
  70: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\thread\mod.rs:477
  71: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\thread\mod.rs:477
  72: panic_unwind::__rust_maybe_catch_panic
             at /rustc/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src/libpanic_unwind\lib.rs:102
  73: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  74: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  75: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  76: std::panicking::try
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\libstd\panicking.rs:289
  77: alloc::boxed::{{impl}}::call_once
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\liballoc\boxed.rs:683
  78: alloc::boxed::{{impl}}::call_once
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\liballoc\boxed.rs:683
  79: alloc::boxed::{{impl}}::call_once
             at \rustc\6b9b97bd9b704f85f0184f7a213cc4d62bd9654c\src\liballoc\boxed.rs:683
  80: BaseThreadInitThunk
  81: RtlUserThreadStart
```

**Comment by steamroller-airmash** [comment]
Closing since this *should* be mitigated by the variety of hardening work that's been done recently.
If it resurfaces then we can reopen this issue (or create a new one).
