### ISSUE TITLE
CTF Crash when a player leaves

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#85]
## Probable Issue
Most likely the dependencies for `ForceUpdate` are incorrect and it's either running too early in the frame or during the next frame.

## Extra Info
Here's the crash log
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WrongGeneration(WrongGeneration { action: "insert component for entity", actual_gen: Generation(-1), entity: Entity(9, Generation(1)) })', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:210
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:224
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:487
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:394
   6: rust_begin_unwind
             at src/libstd/panicking.rs:321
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libcore/macros.rs:26
   9: <airmash_server_ctf::systems::on_flag::force_update::ForceUpdate as airmash_server::utils::event_handler::EventHandler<'a>>::on_event
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libcore/result.rs:808
             at ctf/src/systems/on_flag/force_update.rs:39
  10: <airmash_server::utils::event_handler::EventHandlerWrapper<T> as shred::system::System<'a>>::run
             at ./build/server/src/utils/event_handler.rs:50
  11: <T as shred::system::RunNow<'a>>::run_now
             at ./build/server/src/dispatch/syswrapper.rs:50
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.1/src/system.rs:125
  12: shred::dispatch::dispatcher::Dispatcher::dispatch_seq
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.1/src/dispatch/stage.rs:111
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.1/src/dispatch/dispatcher.rs:84
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./build/server/src/server/server.rs:50
             at ./build/server/src/server/server.rs:100
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libcore/ops/function.rs:286
  14: <futures::stream::take_while::TakeWhile<S, P, R> as futures::stream::Stream>::poll
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libcore/option.rs:424
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/map.rs:79
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/take_while.rs:89
  15: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/for_each.rs:45
  16: futures::task_impl::std::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  17: tokio_current_thread::CurrentRunner::set_spawn
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/scheduler.rs:354
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/scheduler.rs:333
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:779
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:816
  18: <tokio_current_thread::scheduler::Scheduler<U>>::tick
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:778
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:309
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:255
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:776
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/scheduler.rs:333
  19: <tokio_current_thread::Entered<'a, P>>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:605
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:556
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.4/src/lib.rs:499
  20: <std::thread::local::LocalKey<T>>::with
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:195
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:228
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:192
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:309
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:255
  21: <std::thread::local::LocalKey<T>>::with
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:162
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:226
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/timer/handle.rs:94
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:309
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:255
  22: <std::thread::local::LocalKey<T>>::with
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/timer/handle.rs:81
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:219
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/clock/clock.rs:136
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:309
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:255
  23: <std::thread::local::LocalKey<T>>::with
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.8/src/clock/clock.rs:119
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:218
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.7/src/lib.rs:229
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:309
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/thread/local.rs:255
  24: tokio::runtime::current_thread::runtime::Runtime::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.7/src/lib.rs:212
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:217
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.13/src/runtime/current_thread/runtime.rs:195
  25: <airmash_server::server::server::AirmashServer<T>>::run
             at ./build/server/src/server/server.rs:104
  26: airmash_server_ctf::main
             at ctf/src/main.rs:90
  27: std::rt::lang_start::{{closure}}
             at ./rustc/f4a421ee3cf1259f0750ac7fabd19da1d8551e4c/src/libstd/rt.rs:74
  28: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:306
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  30: std::rt::lang_start_internal
             at src/libstd/panicking.rs:285
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  31: main
```

**Comment by steamroller-airmash** [comment]
Fixed in commit `fed80d3`

**Comment by BlackCrawler** [comment]
Latest master crashed with similar error:
<details><summary>backtrace</summary>
<p>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WrongGeneration(WrongGeneration { action: "insert component for entity", actual_gen: Generation(7), entity: Entity(1128, Generation(6)) })', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at ./rustc/04b88a9eba8abbac87eddcb2998beea09589c2c9/src/libcore/result.rs:852
  12: <airmash_server::systems::handlers::game::on_player_powerup::set_powerup_lifetime::SetPowerupLifetime as airmash_server::utils::event_handler::EventHandler>::on_event
             at server/src/systems/handlers/game/on_player_powerup/set_powerup_lifetime.rs:26
  13: <airmash_server::utils::event_handler::EventHandlerWrapper<T> as shred::system::System>::run
             at server/src/utils/event_handler.rs:81
  14: <airmash_server::dispatch::syswrapper::SystemWrapper<T> as shred::system::System>::run
             at server/src/dispatch/syswrapper.rs:50
  15: <T as shred::system::RunNow>::run_now
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/system.rs:133
  16: shred::dispatch::stage::Stage::execute_seq
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/stage.rs:119
  17: shred::dispatch::dispatcher::Dispatcher::dispatch_seq
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/dispatcher.rs:101
  18: airmash_server::server::server::AirmashServer<T>::game_loop
             at ./build/server/src/server/server.rs:47
  19: airmash_server::server::server::AirmashServer<T>::run
             at ./build/server/src/server/server.rs:100
  20: airmash_server_ctf::main
             at ctf/src/main.rs:93
  21: std::rt::lang_start::{{closure}}
             at ./rustc/04b88a9eba8abbac87eddcb2998beea09589c2c9/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  25: std::panicking::try
             at src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: main
```
</p>
</details>

**Comment by steamroller-airmash** [comment]
If you come across any more of these please send them my way :) Fixing all of these is a bit of a game of whack-a-mole.
